import os
import json

class POSTagger:
    def __init__(self, data_dir):
        self.data_dir = data_dir
        self.pos_dict = self._load_pos_dictionary()
        
        # Suffix rules for Nepali POS tagging
        self.suffix_rules = [
            ('haru', 'NOUN'),       # Plural marker
            ('lai', 'ADP'),         # Dative/Accusative marker
            ('ma', 'ADP'),          # Locative marker
            ('ko', 'ADP'),          # Genitive marker
            ('le', 'ADP'),          # Ergative/Instrumental marker
            ('ek', 'ADJ'),          # Adjectival suffix
            ('dain', 'VERB'),       # Negative verb suffix
            ('yo', 'VERB'),         # Past tense
            ('ne', 'VERB'),         # Future/infinitive
            ('chha', 'VERB'),       # Existence/state
            ('chhu', 'VERB'),       # I am
            ('thiyo', 'VERB'),      # Was
            ('nu', 'VERB'),         # Infinitive
            ('ai', 'ADV'),          # Emphasis/Adverbial
            ('ta', 'PART'),         # Particle
            ('ni', 'PART'),         # Particle
        ]
        
    def _load_pos_dictionary(self):
        """Load POS tags from dictionary file."""
        pos_dict = {}
        # Try JSON first (generated by script)
        json_path = os.path.join(self.data_dir, 'id_pos_dict.json')
        if os.path.exists(json_path):
            with open(json_path, 'r', encoding='utf-8') as f:
                pos_dict = json.load(f)
            return pos_dict
            
        # Fallback to Text file if JSON missing
        dict_path = os.path.join(self.data_dir, 'nepali_pos_dict.txt')
        if os.path.exists(dict_path):
            with open(dict_path, 'r', encoding='utf-8') as f:
                for line in f:
                    if ',' in line:
                        word, tag = line.strip().split(',', 1)
                        pos_dict[word.strip()] = tag.strip()
        else:
             # Basic fallback
             pos_dict = {
                'नेपाल': 'NN', 'सरकार': 'NN', 'मेरो': 'PRP', 'छ': 'VB'
            }
        return pos_dict

    def _create_dummy_dictionary(self, path):
        # Deprecated: We use the logic above instead
        pass

    def tag_word(self, word):
        """Tag a single word."""
        # 1. Dictionary Lookup
        if word in self.pos_dict:
            return self.pos_dict[word]
            
        # 2. Heuristics (Suffixes) - Simple fallback for OOV
        if word.endswith('हरू'):
            return 'NN' # Plural noun
        if word.endswith('को') or word.endswith('मा'):
            return 'NN' # Likely noun with case marker
            
        # 3. Check suffix rules (original logic, if not handled by new dict/heuristics)
        for suffix, tag in self.suffix_rules:
            if word.endswith(suffix):
                return tag
                
        # 4. Default fallback
        # Heuristics: Short words likely functional, long words likely content
        if len(word) < 3:
            return 'PART' # Particle/Conjunction/Pronoun
        
        return 'NOUN' # Default open class

    def tag_sentence(self, sentence):
        """Tag a full sentence (string)."""
        words = sentence.split()
        return [(word, self.tag_word(word)) for word in words]
